server:
  port: 30000

spring:
  application:
    name: gulimall-third-party

  # Nacos配置
  cloud:
    nacos:
      # 统一配置：discovery（服务管理）与 config（配置管理）
      # 服务管理 与 配置管理共同地址（也可以分别配置）
      server-addr: 192.168.10.200:8848
      # 服务管理
      discovery:
        enabled: true
      # 配置管理
      config:
        enabled: true
        namespace: 36de42df-90ed-41c6-a00d-0e8dc60eb153

  # Nacos配置服务指定配置源
  config:
    import:
      # 指定data-id
      - optional:nacos:gulimall-third-party.yaml